### ISSUE TITLE
Your app is level 0

### ISSUE THREAD

**Issue by maniackcrudelis** [LowMem/kresus_ynh#12]
Hi,

Your app doesn't work on our CI and is currently level 0.
https://ci-apps.yunohost.org/jenkins/job/kresus%20(Community)/23/console

Your app will be moved at 'notworking' status by the end of this week, on May, 27 if nothing is done before to make it work.

**Comment by LowMem** [comment]
Is app working better, now that I accepted [this pull request](https://github.com/LowMem/kresus_ynh/pull/11) ?

**Comment by LowMem** [comment]
I have made a pull request to include this app to contributed YNH applications: https://github.com/YunoHost/apps/pull/572

Let's close this issue and open another one, when (if ? ;-) ) any problem occur.
