### ISSUE TITLE
Install script directly branched to the dev repo

### ISSUE THREAD

**Issue by ZeHiro** [LowMem/kresus_ynh#2]
Currently, install script is directly branched to the developpment repo, which is not recommanded as some bug may stay, it is recommanded to install kresus through npm

**Comment by LowMem** [comment]
Hello and thanks for reporting this issue.

I have followed [*Global setup* section of kresus' documentation](https://framagit.org/bnjbvr/kresus#global-setup).
Is there any documentation on how to 

> install kresus through npm

 on Debian Jessie ?

**Comment by ZeHiro** [comment]
`sudo npm install kresus` 
I didn't try to intall it on jessie. 
Do no hesitate to come on our irc channel: #kresus on freende.
