### ISSUE TITLE
Consider using the kresus config file

### ISSUE THREAD

**Issue by ZeHiro** [LowMem/kresus_ynh#4]
Next version of Kresus introduces a config file for admin level parameters. It not yet merged, but should be soon https://framagit.org/bnjbvr/kresus/merge_requests/450

**Comment by LowMem** [comment]
Let's wait for next version of Kresus to go all the way to npm: maybe YNH will be available for Debian stretch then ! ? :-D

**Comment by ZeHiro** [comment]
This was more of a warning that things will change, and make it easier for the packaging/admin of kresus

**Comment by bnjbvr** [comment]
Bump for this: the newer version 0.12 has been published on npm today. Thanks!

**Comment by LowMem** [comment]
I was not able to run kresus on Debian Jessie: see [this bug report](https://framagit.org/bnjbvr/kresus/issues/681).

Is there anything I can do to help investigate ?

**Comment by bnjbvr** [comment]
I've answered there, but for history: Kresus needs node v4 at least. Hopefully YNH has a way to juggle between versions of node... Sorry for the trouble caused here!

**Comment by njoyard** [comment]
I'm considering writing a PR that reuses what's done in [cryptpad_ynh](https://github.com/YunoHost-Apps/cryptpad_ynh/) to install a custom node version (using n). Thoughts ?

**Comment by LowMem** [comment]
Is it still current ?

(If so,please re-open this issue.)

**Comment by ZeHiro** [comment]
The new version of the package uses the config file. Thanks.
