### ISSUE TITLE
Potential outdated weboob version

### ISSUE THREAD

**Issue by bnjbvr** [LowMem/kresus_ynh#5]
Hi!

Thanks a lot for packaging Kresus, it's awesome!

I've just skimmed at the install script today, and I've seen weboob was installed from the pipy directory. I think the weboob authors don't release this often, so kresus users on YNH might get an outdated version of weboob.

Moreover, there are a few Python dependencies which might not be included by default and need to be installed by hand.

See the instructions the Dockerfile is using as an example of which python dependencies are needed, etc: https://github.com/bnjbvr/kresus/blob/master/docker/Dockerfile-stable#L4-L16
Then we have a script that clones/updates Weboob's source directory, then fetches all dependencies explicitly needed by weboob: https://github.com/bnjbvr/kresus/blob/master/docker/entrypoint.sh#L19-L35

Not sure if this is applicable to YNH. Hope this helps, though!

Keep up the good work!

**Comment by LowMem** [comment]
Hello,
thanks for your interest !


Are there lot of features used by Kresus from npm repo that are using missing functionalities of Weboob from pip repo ?

I am not familiar with Docker nor nodejs, but I am not fond of downloading/compiling/installing from source:
- code downloaded from master branch can be broken at anytime…
- compilation can take aaaaaaaages. Not only when testing again and again, but also when installing on a an embedded system like [Internet Cube](https://internetcu.be/)/[Brique Internet](https://labriqueinter.net), which is based on an [Olimex board](https://www.olimex.com/Products/OLinuXino/A20/A20-OLinuXIno-LIME2/open-source-hardware)…
- upgrading version needs to go down the road all again…

YunoHost is (for now) based on Debian Jessie.

When I told weboob project, that they might have an outdated version there, I was told to use ``pip install weboob``.
When this YunoHost package was downloading and compiling for installation Kresus from master branch, an issue was submitted to avoid so: [Install script directly branched to the dev repo](https://github.com/LowMem/kresus_ynh/issues/2).

**Comment by bnjbvr** [comment]
If the weboob maintainers advise to use `pip` and update regularily, this shouldn't be an issue, thanks. If this makes any sense, it'd be nice to include a `pip update weboob` in an update script, if there is such a thing.

**Comment by LowMem** [comment]
I fully agree and add this in the corresponding milestone.

By the way, is the ``pip update weboob`` command used when updating weboob from kresus settings' GUI ?

Here is a screenshot of my installation:
![2017-10-22_11-06-48_weboob_update_from_kresus](https://user-images.githubusercontent.com/22399187/31860421-1f577c3e-b71a-11e7-8ac1-0d8d4ddac6b9.png)

**Comment by bnjbvr** [comment]
Ha, our help message could be much clearer here: updating from Kresus only updates the **modules** (pieces of code for each scrapped website), not the core Weboob (framework and tools). To be clear, I think the YNH package should handle the core Weboob update (which can be done through `pip update weboob`). Modules update happen automatically in Kresus on every automatic poll. Thanks!

**Comment by Phyks** [comment]
> If the weboob maintainers advise to use pip and update regularily, this shouldn't be an issue, thanks. If this makes any sense, it'd be nice to include a pip update weboob in an update script, if there is such a thing.

I think `pypi` only has the current stable release of Weboob (1.3 as of writing this message), not the `devel` release (https://git.weboob.org/weboob/devel/).

@bnjbvr You have more feedback on this than I do, but I think it is more advisable to use `devel` as it gets updates quicker, isn't it?

**Comment by bnjbvr** [comment]
Yes, as far as I know the stable version can have some extended periods without modules working (since it can be a gigantic burden to do the backports), so it's usually preferred to use the devel version.

**Comment by LowMem** [comment]
I am not comfortable using a dev version on a « production » environment…

Is this still current ? (if so please re-open this issue.)
