### ISSUE TITLE
Consider using NodeJS from the official repos

### ISSUE THREAD

**Issue by Phyks** [LowMem/kresus_ynh#8]
Hi,

`nodejs` (respectively `nodejs-legacy`) from the Debian packages is stuck at version 0.10 (for now, in `jessie` which is used by Yunohost) and will be at version 4 (in `stretch`, current Debian `stable`).

Latest Kresus release (0.12) requires Node v4, so it won't work out of the box with the `jessie` packages. Using the version from the backport could do the trick, but `npm` is not packaged in the backports :/

Next release of Kresus will require Node v6, which is the current LTS and which is not available either in `jessie` or `stretch` repos.

So, I think the best and safest option would be to use [the official Node repos for the v6](https://nodejs.org/en/download/package-manager/#debian-and-ubuntu-based-linux-distributions). This will install v6 which is the current LTS, compatible with both current and next release of Kresus. It will also install an updated `npm`.

Just keep in mind that this method will not work on ARMv6 hardware (Raspberry Pi 1).

cc @elvirolo

EDIT: Apparently, something is already available on YNH side to install Node: https://github.com/YunoHost-Apps/etherpad_mypads_ynh/blob/master/scripts/_common.sh#L98-L221.

**Comment by LowMem** [comment]
As it was mentionned on [this YNH forum discussion](https://forum.yunohost.org/t/kresus-app-please-test/3546/27?u=lowmem) There are other YNH apps using nodejs out there ! \o/

Code about nodejs usage in YNH is available here: https://github.com/YunoHost-Apps/etherpad_mypads_ynh/blob/master/scripts/_common.sh#L98-L221

**Comment by LowMem** [comment]
Is this stil current ?

(If so, please re-open this issue.)
