### ISSUE TITLE
Error 502 : Bad gateway from Cloudflare

### ISSUE THREAD

**Issue by Tibbob** [LowMem/kresus_ynh#9]
Hello,

I've got an issue : after installing Kresus, Cloudflare sends me a 502 error (Error 502 : Bad gateway) and the Yunohost interface seems to crash (the API does not respond for a few seconds).

Do you have any idea what this can come from? (Cloudflare ?)

**Comment by LowMem** [comment]
No idea, sorry.

Is your issue still current ? (if so please feel free to re-open it.)
